package com.aubay.men.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FonctionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFonctionAllPropertiesEquals(Fonction expected, Fonction actual) {
        assertFonctionAutoGeneratedPropertiesEquals(expected, actual);
        assertFonctionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFonctionAllUpdatablePropertiesEquals(Fonction expected, Fonction actual) {
        assertFonctionUpdatableFieldsEquals(expected, actual);
        assertFonctionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFonctionAutoGeneratedPropertiesEquals(Fonction expected, Fonction actual) {
        assertThat(expected)
            .as("Verify Fonction auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFonctionUpdatableFieldsEquals(Fonction expected, Fonction actual) {
        assertThat(expected)
            .as("Verify Fonction relevant properties")
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFonctionUpdatableRelationshipsEquals(Fonction expected, Fonction actual) {}
}
