package com.aubay.men.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaterielProfilAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielProfilAllPropertiesEquals(MaterielProfil expected, MaterielProfil actual) {
        assertMaterielProfilAutoGeneratedPropertiesEquals(expected, actual);
        assertMaterielProfilAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielProfilAllUpdatablePropertiesEquals(MaterielProfil expected, MaterielProfil actual) {
        assertMaterielProfilUpdatableFieldsEquals(expected, actual);
        assertMaterielProfilUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielProfilAutoGeneratedPropertiesEquals(MaterielProfil expected, MaterielProfil actual) {
        assertThat(expected)
            .as("Verify MaterielProfil auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielProfilUpdatableFieldsEquals(MaterielProfil expected, MaterielProfil actual) {
        assertThat(expected)
            .as("Verify MaterielProfil relevant properties")
            .satisfies(e -> assertThat(e.getDureeHebdo()).as("check dureeHebdo").isEqualTo(actual.getDureeHebdo()))
            .satisfies(e -> assertThat(e.getEstNeuf()).as("check estNeuf").isEqualTo(actual.getEstNeuf()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielProfilUpdatableRelationshipsEquals(MaterielProfil expected, MaterielProfil actual) {
        assertThat(expected)
            .as("Verify MaterielProfil relationships")
            .satisfies(e -> assertThat(e.getProfils()).as("check profils").isEqualTo(actual.getProfils()))
            .satisfies(e -> assertThat(e.getPrestations()).as("check prestations").isEqualTo(actual.getPrestations()))
            .satisfies(e -> assertThat(e.getMateriels()).as("check materiels").isEqualTo(actual.getMateriels()));
    }
}
