package com.aubay.men.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaterielAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielAllPropertiesEquals(Materiel expected, Materiel actual) {
        assertMaterielAutoGeneratedPropertiesEquals(expected, actual);
        assertMaterielAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielAllUpdatablePropertiesEquals(Materiel expected, Materiel actual) {
        assertMaterielUpdatableFieldsEquals(expected, actual);
        assertMaterielUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielAutoGeneratedPropertiesEquals(Materiel expected, Materiel actual) {
        assertThat(expected)
            .as("Verify Materiel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielUpdatableFieldsEquals(Materiel expected, Materiel actual) {
        assertThat(expected)
            .as("Verify Materiel relevant properties")
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()))
            .satisfies(e -> assertThat(e.getFeVeille()).as("check feVeille").isEqualTo(actual.getFeVeille()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterielUpdatableRelationshipsEquals(Materiel expected, Materiel actual) {
        assertThat(expected)
            .as("Verify Materiel relationships")
            .satisfies(e -> assertThat(e.getMaterielProfils()).as("check materielProfils").isEqualTo(actual.getMaterielProfils()));
    }
}
