package com.aubay.men.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TransportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportAllPropertiesEquals(Transport expected, Transport actual) {
        assertTransportAutoGeneratedPropertiesEquals(expected, actual);
        assertTransportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportAllUpdatablePropertiesEquals(Transport expected, Transport actual) {
        assertTransportUpdatableFieldsEquals(expected, actual);
        assertTransportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportAutoGeneratedPropertiesEquals(Transport expected, Transport actual) {
        assertThat(expected)
            .as("Verify Transport auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportUpdatableFieldsEquals(Transport expected, Transport actual) {
        assertThat(expected)
            .as("Verify Transport relevant properties")
            .satisfies(e -> assertThat(e.getCategorie()).as("check categorie").isEqualTo(actual.getCategorie()))
            .satisfies(e -> assertThat(e.getTypeMoteur()).as("check typeMoteur").isEqualTo(actual.getTypeMoteur()))
            .satisfies(e -> assertThat(e.getFeKm()).as("check feKm").isEqualTo(actual.getFeKm()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTransportUpdatableRelationshipsEquals(Transport expected, Transport actual) {
        assertThat(expected)
            .as("Verify Transport relationships")
            .satisfies(e -> assertThat(e.getTransportProfils()).as("check transportProfils").isEqualTo(actual.getTransportProfils()))
            .satisfies(e -> assertThat(e.getDeplacementProfils()).as("check deplacementProfils").isEqualTo(actual.getDeplacementProfils()));
    }
}
