package com.aubay.men.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UniteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteAllPropertiesEquals(Unite expected, Unite actual) {
        assertUniteAutoGeneratedPropertiesEquals(expected, actual);
        assertUniteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteAllUpdatablePropertiesEquals(Unite expected, Unite actual) {
        assertUniteUpdatableFieldsEquals(expected, actual);
        assertUniteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteAutoGeneratedPropertiesEquals(Unite expected, Unite actual) {
        assertThat(expected)
            .as("Verify Unite auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteUpdatableFieldsEquals(Unite expected, Unite actual) {
        assertThat(expected)
            .as("Verify Unite relevant properties")
            .satisfies(e -> assertThat(e.getLibelle()).as("check libelle").isEqualTo(actual.getLibelle()))
            .satisfies(e -> assertThat(e.getEstTemporelle()).as("check estTemporelle").isEqualTo(actual.getEstTemporelle()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUniteUpdatableRelationshipsEquals(Unite expected, Unite actual) {}
}
